"""
utils/report_generator.py
---------------------------
PDF Report Generation Module for HireSense AI.

Generates polished, human-readable PDF reports from the JSON-like result
dictionaries produced by `ml/ats_scorer.py` and `ml/candidate_ranker.py`
(specifically, from calling `.to_dict()` on their result dataclasses).

This module is intentionally decoupled from the ml/ package — it accepts
plain dicts matching documented shapes rather than importing the
dataclasses directly, so it can be tested/used independently and avoids
any risk of circular imports. See the docstrings of each function for
the exact expected dict shape.

Two report types are supported:
    1. Individual Candidate Report — one candidate's full score breakdown.
    2. Batch Ranking Report — a summary table of all ranked candidates
       for a given job description.

Depends on `reportlab` (pure Python, no external binaries needed).
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Optional

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    PageBreak, HRFlowable, KeepTogether,
)

try:
    from utils.helpers import sanitize_filename, get_timestamp, format_score
except ImportError:
    # Allow standalone execution (python utils/report_generator.py).
    from helpers import sanitize_filename, get_timestamp, format_score  # type: ignore

logger = logging.getLogger("hiresense.report_generator")
if not logger.handlers:
    logging.basicConfig(level=logging.INFO)


DISCLAIMER_TEXT = (
    "This compatibility score is generated by HireSense AI for "
    "educational/project demonstration purposes only. It is NOT an "
    "official ATS (Applicant Tracking System) algorithm and should not "
    "be used as the sole basis for real hiring decisions. Methodology "
    "and weights are transparent and configurable."
)

# Brand-ish color palette (kept simple/professional — this is a
# functional report, not a marketing asset).
_COLOR_PRIMARY = colors.HexColor("#1F3A5F")
_COLOR_ACCENT = colors.HexColor("#2E86AB")
_COLOR_SUCCESS = colors.HexColor("#2E7D32")
_COLOR_WARNING = colors.HexColor("#B8860B")
_COLOR_DANGER = colors.HexColor("#C62828")
_COLOR_LIGHT_BG = colors.HexColor("#F2F5F8")
_COLOR_BORDER = colors.HexColor("#D0D7DE")


def _tier_color(tier: str) -> colors.Color:
    """Map a recommendation tier string to a display color."""
    mapping = {
        "Strong Match": _COLOR_SUCCESS,
        "Good Match": _COLOR_ACCENT,
        "Moderate Match": _COLOR_WARNING,
        "Weak Match": _COLOR_DANGER,
        "Unscored": colors.grey,
    }
    return mapping.get(tier, _COLOR_ACCENT)


def _score_color(score: float) -> colors.Color:
    """Map a raw 0-100 score to a display color (used for component
    score cells in tables).
    """
    if score >= 75:
        return _COLOR_SUCCESS
    if score >= 55:
        return _COLOR_ACCENT
    if score >= 35:
        return _COLOR_WARNING
    return _COLOR_DANGER


def _build_styles() -> dict:
    """Build the paragraph style set shared by all reports in this
    module. Centralized so both report types look visually consistent.
    """
    base = getSampleStyleSheet()

    styles = {
        "title": ParagraphStyle(
            "ReportTitle", parent=base["Title"],
            fontSize=20, textColor=_COLOR_PRIMARY, spaceAfter=4,
        ),
        "subtitle": ParagraphStyle(
            "ReportSubtitle", parent=base["Normal"],
            fontSize=11, textColor=colors.grey, spaceAfter=14,
        ),
        "heading": ParagraphStyle(
            "SectionHeading", parent=base["Heading2"],
            fontSize=13, textColor=_COLOR_PRIMARY,
            spaceBefore=14, spaceAfter=6,
        ),
        "body": ParagraphStyle(
            "Body", parent=base["Normal"],
            fontSize=10, leading=14, alignment=TA_LEFT,
        ),
        "small": ParagraphStyle(
            "Small", parent=base["Normal"],
            fontSize=8, leading=11, textColor=colors.grey,
        ),
        "score_big": ParagraphStyle(
            "ScoreBig", parent=base["Normal"],
            fontSize=32, leading=38, alignment=TA_CENTER, textColor=_COLOR_PRIMARY,
            spaceAfter=6,
        ),
        "tier_label": ParagraphStyle(
            "TierLabel", parent=base["Normal"],
            fontSize=12, alignment=TA_CENTER, spaceAfter=10,
        ),
        "disclaimer": ParagraphStyle(
            "Disclaimer", parent=base["Normal"],
            fontSize=8, leading=11, textColor=colors.grey,
            borderPadding=6,
        ),
    }
    return styles


# ============================================================
# Report 1: Individual Candidate Report
# ============================================================

def generate_candidate_report(
    candidate_name: str,
    score_data: dict,
    output_path: str,
    job_title: str = "",
    candidate_id: str = "",
    resume_filename: str = "",
) -> tuple[bool, Optional[str]]:
    """Generate a single-candidate PDF report.

    Expected `score_data` shape (i.e. the output of
    `ATSScoreResult.to_dict()` from ml/ats_scorer.py):
        {
            "total_score": float,
            "components": {
                "skills": {"raw_score": float, "weight_percent": float,
                            "weighted_contribution": float,
                            "details": {"matched_skills": [...],
                                        "missing_skills": [...], ...}},
                "similarity": {...},
                "experience": {...},
                "education": {...},
                "projects": {...},
                "certifications": {...},
            },
            "weights_used": {...},
            "disclaimer": str,
        }

    A "tier" key is optional (e.g. "Strong Match") — if provided it's
    shown next to the score; otherwise it's omitted.

    Returns (success, error_message). Never raises — PDF generation
    failures are caught and reported back as a message.
    """
    try:
        output_file = Path(output_path)
        output_file.parent.mkdir(parents=True, exist_ok=True)

        styles = _build_styles()
        doc = SimpleDocTemplate(
            str(output_file), pagesize=A4,
            topMargin=18 * mm, bottomMargin=16 * mm,
            leftMargin=18 * mm, rightMargin=18 * mm,
            title=f"HireSense AI Report - {candidate_name}",
        )

        story = []
        story.extend(_build_header(styles, "Candidate Compatibility Report", job_title))
        story.extend(_build_candidate_info_block(styles, candidate_name, candidate_id, resume_filename))
        story.extend(_build_score_summary_block(styles, score_data))
        story.extend(_build_component_breakdown_table(styles, score_data))
        story.extend(_build_skills_section(styles, score_data))
        story.append(Spacer(1, 14))
        story.extend(_build_disclaimer_block(styles, score_data.get("disclaimer")))

        doc.build(story)
        logger.info("Candidate report generated: %s", output_file)
        return True, None

    except Exception as exc:  # noqa: BLE001
        logger.exception("Failed to generate candidate report for %s", candidate_name)
        return False, f"Failed to generate PDF report: {exc}"


def _build_header(styles: dict, report_title: str, job_title: str) -> list:
    elements = [
        Paragraph("HireSense AI", styles["title"]),
        Paragraph(report_title, styles["heading"]),
    ]
    if job_title:
        elements.append(Paragraph(f"Position: {job_title}", styles["subtitle"]))
    elements.append(HRFlowable(width="100%", thickness=1, color=_COLOR_BORDER, spaceAfter=10))
    return elements


def _build_candidate_info_block(
    styles: dict, candidate_name: str, candidate_id: str, resume_filename: str
) -> list:
    rows = [["Candidate Name", candidate_name or "N/A"]]
    if candidate_id:
        rows.append(["Candidate ID", candidate_id])
    if resume_filename:
        rows.append(["Resume File", resume_filename])
    rows.append(["Report Generated", get_timestamp().replace("_", " ")])

    table = Table(rows, colWidths=[45 * mm, 120 * mm])
    table.setStyle(TableStyle([
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("TEXTCOLOR", (0, 0), (0, -1), colors.grey),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("LINEBELOW", (0, -1), (-1, -1), 0.5, _COLOR_BORDER),
    ]))
    return [table, Spacer(1, 12)]


def _build_score_summary_block(styles: dict, score_data: dict) -> list:
    total_score = score_data.get("total_score", 0.0)
    tier = score_data.get("tier")

    elements = [
        Paragraph(format_score(total_score, decimals=1), styles["score_big"]),
    ]
    if tier:
        tier_style = ParagraphStyle(
            "TierColored", parent=styles["tier_label"],
            textColor=_tier_color(tier), fontName="Helvetica-Bold",
        )
        elements.append(Paragraph(tier, tier_style))
    else:
        elements.append(Spacer(1, 10))

    elements.append(
        Paragraph(
            "Overall AI-generated compatibility score (see breakdown and "
            "disclaimer below).",
            styles["small"],
        )
    )
    elements.append(Spacer(1, 8))
    return elements


_COMPONENT_LABELS = {
    "skills": "Skills Match",
    "similarity": "Job Description Similarity",
    "experience": "Experience",
    "education": "Education",
    "projects": "Projects",
    "certifications": "Certifications",
}


def _build_component_breakdown_table(styles: dict, score_data: dict) -> list:
    components = score_data.get("components", {})
    if not components:
        return []

    header = ["Component", "Weight", "Raw Score", "Contribution"]
    rows = [header]

    for key, label in _COMPONENT_LABELS.items():
        component = components.get(key)
        if not component:
            continue
        rows.append([
            label,
            f"{component.get('weight_percent', 0)}%",
            f"{component.get('raw_score', 0):.1f}/100",
            f"{component.get('weighted_contribution', 0):.2f} pts",
        ])

    table = Table(rows, colWidths=[60 * mm, 25 * mm, 35 * mm, 35 * mm])
    style_commands = [
        ("BACKGROUND", (0, 0), (-1, 0), _COLOR_PRIMARY),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("ALIGN", (1, 0), (-1, -1), "CENTER"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, _COLOR_LIGHT_BG]),
        ("GRID", (0, 0), (-1, -1), 0.5, _COLOR_BORDER),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]

    # Color-code the raw score column per row based on its value.
    for row_index, key in enumerate([k for k in _COMPONENT_LABELS if k in components], start=1):
        raw_score = components[key].get("raw_score", 0)
        style_commands.append(
            ("TEXTCOLOR", (2, row_index), (2, row_index), _score_color(raw_score))
        )
        style_commands.append(("FONTNAME", (2, row_index), (2, row_index), "Helvetica-Bold"))

    table.setStyle(TableStyle(style_commands))

    return [
        Paragraph("Score Breakdown", styles["heading"]),
        table,
        Spacer(1, 4),
    ]


def _build_skills_section(styles: dict, score_data: dict) -> list:
    skills_component = score_data.get("components", {}).get("skills", {})
    details = skills_component.get("details", {})
    matched = details.get("matched_skills", [])
    missing = details.get("missing_skills", [])

    elements = [Paragraph("Skills Analysis", styles["heading"])]

    matched_style = ParagraphStyle(
        "MatchedSkills", parent=styles["body"], textColor=_COLOR_SUCCESS,
    )
    missing_style = ParagraphStyle(
        "MissingSkills", parent=styles["body"], textColor=_COLOR_DANGER,
    )

    if matched:
        elements.append(Paragraph(
            f"<b>Matched Skills ({len(matched)}):</b> " + ", ".join(matched),
            matched_style,
        ))
    else:
        elements.append(Paragraph("<b>Matched Skills:</b> None detected.", styles["body"]))

    elements.append(Spacer(1, 4))

    if missing:
        elements.append(Paragraph(
            f"<b>Missing Skills ({len(missing)}):</b> " + ", ".join(missing),
            missing_style,
        ))
    else:
        elements.append(Paragraph(
            "<b>Missing Skills:</b> None — all required skills were found.",
            styles["body"],
        ))

    return elements


def _build_disclaimer_block(styles: dict, disclaimer: Optional[str]) -> list:
    text = disclaimer or DISCLAIMER_TEXT
    box_table = Table([[Paragraph(f"<b>Disclaimer:</b> {text}", styles["disclaimer"])]],
                       colWidths=[174 * mm])
    box_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), _COLOR_LIGHT_BG),
        ("BOX", (0, 0), (-1, -1), 0.5, _COLOR_BORDER),
        ("TOPPADDING", (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
    ]))
    return [box_table]


# ============================================================
# Report 2: Batch Ranking Summary Report
# ============================================================

def generate_ranking_report(
    job_title: str,
    ranked_candidates: list[dict],
    output_path: str,
    summary: Optional[dict] = None,
) -> tuple[bool, Optional[str]]:
    """Generate a batch PDF report summarizing all ranked candidates for
    a job description.

    Expected `ranked_candidates` shape — a list of dicts matching
    `RankedCandidate.to_dict()` from ml/candidate_ranker.py:
        [
            {
                "candidate_id": str, "name": str, "rank": int,
                "total_score": float, "tier": str,
                "score_breakdown": {...same shape as generate_candidate_report...},
                "error": str | None,
            },
            ...
        ]

    `summary` is optional — the output of
    `CandidateRanker.summarize_ranking()` (average score, tier counts,
    etc.) — shown at the top if provided.

    Returns (success, error_message). Never raises.
    """
    try:
        output_file = Path(output_path)
        output_file.parent.mkdir(parents=True, exist_ok=True)

        styles = _build_styles()
        doc = SimpleDocTemplate(
            str(output_file), pagesize=A4,
            topMargin=18 * mm, bottomMargin=16 * mm,
            leftMargin=18 * mm, rightMargin=18 * mm,
            title=f"HireSense AI Ranking Report - {job_title}",
        )

        story = []
        story.extend(_build_header(styles, "Candidate Ranking Report", job_title))

        if summary:
            story.extend(_build_summary_block(styles, summary))

        story.extend(_build_ranking_table(styles, ranked_candidates))
        story.append(Spacer(1, 14))
        story.extend(_build_disclaimer_block(styles, None))

        doc.build(story)
        logger.info("Ranking report generated: %s", output_file)
        return True, None

    except Exception as exc:  # noqa: BLE001
        logger.exception("Failed to generate ranking report for job '%s'", job_title)
        return False, f"Failed to generate PDF report: {exc}"


def _build_summary_block(styles: dict, summary: dict) -> list:
    rows = [
        ["Total Candidates", str(summary.get("total_candidates", 0))],
        ["Successfully Scored", str(summary.get("scored_candidates", 0))],
        ["Average Score", f"{summary.get('average_score', 0):.1f}/100"],
        ["Top Score", f"{summary.get('top_score', 0):.1f}/100"],
    ]

    tier_counts = summary.get("tier_counts", {})
    if tier_counts:
        tier_summary = ", ".join(f"{tier}: {count}" for tier, count in tier_counts.items())
        rows.append(["Tier Breakdown", tier_summary])

    table = Table(rows, colWidths=[45 * mm, 120 * mm])
    table.setStyle(TableStyle([
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("TEXTCOLOR", (0, 0), (0, -1), colors.grey),
        ("BACKGROUND", (0, 0), (-1, -1), _COLOR_LIGHT_BG),
        ("BOX", (0, 0), (-1, -1), 0.5, _COLOR_BORDER),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    return [Paragraph("Summary", styles["heading"]), table, Spacer(1, 10)]


def _build_ranking_table(styles: dict, ranked_candidates: list[dict]) -> list:
    if not ranked_candidates:
        return [Paragraph("No candidates to display.", styles["body"])]

    header = ["Rank", "Candidate", "Score", "Tier", "Matched Skills"]
    rows = [header]

    for candidate in ranked_candidates:
        breakdown = candidate.get("score_breakdown") or {}
        skills_details = (
            breakdown.get("components", {}).get("skills", {}).get("details", {})
        )
        matched_count = len(skills_details.get("matched_skills", []))
        required_count = skills_details.get("required_skill_count", 0)

        if candidate.get("error"):
            score_display = "N/A"
            tier_display = "Unscored"
            skills_display = candidate["error"]
        else:
            score_display = f"{candidate.get('total_score', 0):.1f}"
            tier_display = candidate.get("tier", "")
            skills_display = f"{matched_count}/{required_count}" if required_count else str(matched_count)

        rows.append([
            str(candidate.get("rank", "")),
            candidate.get("name", "Unknown"),
            score_display,
            tier_display,
            skills_display,
        ])

    table = Table(rows, colWidths=[15 * mm, 50 * mm, 22 * mm, 32 * mm, 35 * mm])
    style_commands = [
        ("BACKGROUND", (0, 0), (-1, 0), _COLOR_PRIMARY),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("ALIGN", (0, 0), (0, -1), "CENTER"),
        ("ALIGN", (2, 0), (2, -1), "CENTER"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, _COLOR_LIGHT_BG]),
        ("GRID", (0, 0), (-1, -1), 0.5, _COLOR_BORDER),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]

    for row_index, candidate in enumerate(ranked_candidates, start=1):
        if not candidate.get("error"):
            tier_color = _tier_color(candidate.get("tier", ""))
            style_commands.append(
                ("TEXTCOLOR", (3, row_index), (3, row_index), tier_color)
            )
            style_commands.append(("FONTNAME", (3, row_index), (3, row_index), "Helvetica-Bold"))

    table.setStyle(TableStyle(style_commands))

    return [Paragraph("Ranked Candidates", styles["heading"]), table]


if __name__ == "__main__":
    # Simple manual smoke test when run directly:
    #   python utils/report_generator.py
    sample_score_data = {
        "total_score": 78.4,
        "tier": "Good Match",
        "components": {
            "skills": {
                "raw_score": 80.0, "weight_percent": 30.0,
                "weighted_contribution": 24.0,
                "details": {
                    "matched_skills": ["python", "django", "aws"],
                    "missing_skills": ["kubernetes"],
                    "required_skill_count": 4,
                },
            },
            "similarity": {"raw_score": 65.2, "weight_percent": 25.0, "weighted_contribution": 16.3, "details": {}},
            "experience": {"raw_score": 70.0, "weight_percent": 20.0, "weighted_contribution": 14.0, "details": {}},
            "education": {"raw_score": 70.0, "weight_percent": 10.0, "weighted_contribution": 7.0, "details": {}},
            "projects": {"raw_score": 75.0, "weight_percent": 10.0, "weighted_contribution": 7.5, "details": {}},
            "certifications": {"raw_score": 33.3, "weight_percent": 5.0, "weighted_contribution": 1.67, "details": {}},
        },
        "disclaimer": DISCLAIMER_TEXT,
    }

    ok, err = generate_candidate_report(
        candidate_name="Alice Smith",
        score_data=sample_score_data,
        output_path="/tmp/sample_candidate_report.pdf",
        job_title="Software Engineer",
        candidate_id="alice-smith-001",
        resume_filename="alice_resume.pdf",
    )
    print("Candidate report:", ok, err)

    sample_ranked = [
        {"candidate_id": "1", "name": "Alice Smith", "rank": 1, "total_score": 78.4,
         "tier": "Good Match", "score_breakdown": sample_score_data, "error": None},
        {"candidate_id": "2", "name": "Bob Lee", "rank": 2, "total_score": 22.1,
         "tier": "Weak Match", "score_breakdown": None, "error": None},
    ]
    sample_summary = {
        "total_candidates": 2, "scored_candidates": 2, "average_score": 50.25,
        "top_score": 78.4, "tier_counts": {"Good Match": 1, "Weak Match": 1},
    }

    ok2, err2 = generate_ranking_report(
        job_title="Software Engineer",
        ranked_candidates=sample_ranked,
        output_path="/tmp/sample_ranking_report.pdf",
        summary=sample_summary,
    )
    print("Ranking report:", ok2, err2)
    