"""
HireSense AI - Report Generation Page
==========================================================================
Lets a recruiter configure and download a report (PDF where possible)
summarizing the candidate pool or a single candidate.

MOCK / PLACEHOLDER NOTICE
------------------------------------------------------------------------
The real report-building logic is expected to live in
`utils/report_generator.py` (per project structure), e.g.:

    from utils.report_generator import generate_report
    pdf_bytes = generate_report(candidates=..., options=...)

That module does not exist yet, so this page tries to import it and,
if unavailable, falls back to a locally-built lightweight PDF (via
`fpdf`, if installed) purely so the "Generate & Download" flow is
demonstrable end-to-end during UI development. If neither is
available, it degrades further to a plain-text report so the button
never dead-ends. None of this fallback logic should be needed once
`utils/report_generator.py` is implemented — swap the import and
delete `_fallback_build_report()`.
"""

from __future__ import annotations

import io
from datetime import datetime

import streamlit as st

from ui.styles import COLORS
from ui.components import (
    render_section_header,
    render_label,
    render_badge,
    render_empty_state,
    render_success,
    render_divider,
)
from ui.ranking import get_ranked_candidates
from ui.candidate_details import get_candidate_detail


# ======================================================================
# REPORT TYPES
# ======================================================================

REPORT_TYPES = {
    "Full Ranking Summary": "All screened candidates with scores, skills, and status.",
    "Shortlisted Only": "Only candidates currently marked as shortlisted.",
    "Individual Candidate": "A deep-dive profile for one selected candidate.",
}


# ======================================================================
# FALLBACK REPORT BUILDER  (placeholder only — see module docstring)
# ======================================================================

def _fallback_build_report(title: str, lines: list[str]) -> tuple[bytes, str, str]:
    """
    Build a downloadable report locally when utils.report_generator is
    not yet available. Tries a real PDF via fpdf; falls back to plain
    text if fpdf isn't installed. Returns (bytes, file_extension, mime_type).
    """
    try:
        from fpdf import FPDF  # lightweight, commonly available

        pdf = FPDF()
        pdf.add_page()
        pdf.set_font("Helvetica", "B", 16)
        pdf.cell(0, 10, title, ln=True)
        pdf.set_font("Helvetica", "", 10)
        pdf.cell(0, 8, f"Generated by HireSense AI on {datetime.now().strftime('%Y-%m-%d %H:%M')}", ln=True)
        pdf.ln(4)
        pdf.set_font("Helvetica", "", 11)
        for line in lines:
            pdf.multi_cell(0, 7, line)
        buffer = pdf.output(dest="S")
        pdf_bytes = bytes(buffer) if not isinstance(buffer, (bytes, bytearray)) else bytes(buffer)
        return pdf_bytes, "pdf", "application/pdf"
    except ImportError:
        text_content = title + "\n"
        text_content += f"Generated by HireSense AI on {datetime.now().strftime('%Y-%m-%d %H:%M')}\n\n"
        text_content += "\n".join(lines)
        return text_content.encode("utf-8"), "txt", "text/plain"


def _build_report_lines(report_type: str, candidates: list[dict], options: dict, candidate_name: str | None) -> tuple[str, list[str]]:
    """Assemble the plain-text content that goes into the report."""
    if report_type == "Individual Candidate" and candidate_name:
        detail = get_candidate_detail(candidate_name)
        title = f"Candidate Report: {detail['name']}"
        lines = [
            f"Role: {detail['role']}",
            f"Experience: {detail['experience']}",
            f"Compatibility Score: {detail['score']:.0f}%",
            f"Recommendation: {detail['recommendation']}",
            f"Status: {detail['status'].title()}",
            "",
            "Matched Skills: " + ", ".join(detail["matched_skills"]),
            "Missing Skills: " + ", ".join(detail["missing_skills"]) if detail["missing_skills"] else "Missing Skills: None",
            "",
            f"Education: {detail['education']}",
        ]
        if options.get("include_recommendations"):
            lines += ["", "Strengths:"] + [f"  - {s}" for s in detail["strengths"]]
            lines += ["", "Areas for Improvement:"] + [f"  - {i}" for i in detail["improvements"]]
        return title, lines

    if report_type == "Shortlisted Only":
        pool = [c for c in candidates if c["status"] == "shortlisted"]
        title = "Shortlisted Candidates Report"
    else:
        pool = candidates
        title = "Full Candidate Ranking Report"

    lines = [f"Total candidates in report: {len(pool)}", ""]
    for i, c in enumerate(pool, start=1):
        lines.append(f"{i}. {c['name']} — {c['role']} — Score: {c['score']:.0f}% — Status: {c['status'].title()}")
        if options.get("include_skill_breakdown"):
            lines.append(f"   Skills: {', '.join(c['matched_skills'])}")
        if options.get("include_recommendations"):
            lines.append(f"   Recommendation: {c['recommendation']}")
    return title, lines


# ======================================================================
# PAGE RENDER
# ======================================================================

def render() -> None:
    render_section_header(
        "Report Generation",
        "Configure and export a candidate report for stakeholders.",
        icon="🧾",
    )

    candidates = get_ranked_candidates()

    if not candidates:
        render_empty_state(
            "No candidates to report on yet",
            "Screen resumes from the Resume Screening page before generating a report.",
            icon="🧾",
        )
        return

    # ------------------------------------------------------------
    # CONFIGURATION
    # ------------------------------------------------------------
    config_col, preview_col = st.columns([1.1, 1])

    with config_col:
        render_label("REPORT TYPE")
        report_type = st.radio(
            "Report type",
            options=list(REPORT_TYPES.keys()),
            label_visibility="collapsed",
        )
        st.caption(REPORT_TYPES[report_type])

        candidate_name = None
        if report_type == "Individual Candidate":
            candidate_name = st.selectbox(
                "Select candidate",
                options=[c["name"] for c in candidates],
            )

        st.markdown("<div style='margin-top:0.75rem;'></div>", unsafe_allow_html=True)
        render_label("INCLUDE IN REPORT")
        include_skills = st.checkbox("Skill breakdown", value=True)
        include_recs = st.checkbox("Recommendations & rationale", value=True)
        include_charts_note = st.checkbox(
            "Analytics summary (score/skill charts)", value=False,
            help="Chart embedding will be available once utils/report_generator.py is integrated.",
        )

        options = {
            "include_skill_breakdown": include_skills,
            "include_recommendations": include_recs,
            "include_charts": include_charts_note,
        }

    with preview_col:
        render_label("PREVIEW")
        pool_size = (
            1 if report_type == "Individual Candidate"
            else len([c for c in candidates if c["status"] == "shortlisted"]) if report_type == "Shortlisted Only"
            else len(candidates)
        )
        st.markdown(
            f"""
            <div class="glass-card">
                <div style="font-weight:700; color:{COLORS['text_primary']}; font-size:1rem;">{report_type}</div>
                <div style="font-size:0.82rem; color:{COLORS['text_muted']}; margin-top:0.25rem;">
                    {pool_size} candidate(s) included
                </div>
                <div style="margin-top:0.75rem; display:flex; flex-wrap:wrap; gap:0.4rem;">
                    {'<span class="badge badge-primary">Skill Breakdown</span>' if include_skills else ''}
                    {'<span class="badge badge-primary">Recommendations</span>' if include_recs else ''}
                    {'<span class="badge badge-accent">Analytics Summary</span>' if include_charts_note else ''}
                </div>
            </div>
            """,
            unsafe_allow_html=True,
        )

    render_divider()

    # ------------------------------------------------------------
    # GENERATE + DOWNLOAD
    # ------------------------------------------------------------
    generate_col, _sp = st.columns([1, 2])
    with generate_col:
        generate_clicked = st.button("📄  Generate Report", type="primary", use_container_width=True)

    if generate_clicked:
        with st.spinner("Building report…"):
            title, lines = _build_report_lines(report_type, candidates, options, candidate_name)

            # Prefer the real report generator if it exists; otherwise fall back.
            try:
                from utils.report_generator import generate_report  # future real implementation
                report_bytes = generate_report(title=title, lines=lines, candidates=candidates, options=options)
                file_ext, mime_type = "pdf", "application/pdf"
            except ImportError:
                report_bytes, file_ext, mime_type = _fallback_build_report(title, lines)

        render_success("Report generated successfully.")

        safe_name = (candidate_name or report_type).replace(" ", "_").lower()
        filename = f"hiresense_report_{safe_name}_{datetime.now().strftime('%Y%m%d')}.{file_ext}"

        st.download_button(
            label=f"⬇️  Download {file_ext.upper()} Report",
            data=report_bytes,
            file_name=filename,
            mime=mime_type,
            use_container_width=True,
        )

        if file_ext != "pdf":
            st.caption(
                "PDF generation library not available in this environment — downloaded as a plain-text "
                "report instead. Install `fpdf2` or implement `utils/report_generator.py` for full PDF output."
            )

    render_divider()
    st.caption(
        "Report content is drawn from a mock candidate dataset for UI development. "
        "Production reports will be generated by utils/report_generator.py once integrated."
    )